### ISSUE TITLE
Issue with SSL certificate chain when querying API from nodejs

### ISSUE THREAD

**Issue by jeanregisser** [bi23com/thecelo#3]
Hi,

I came across an issue (`unable to verify the first certificate`) when querying the API from a nodejs environment:

<img width="793" alt="Screenshot 2020-11-30 at 09 26 22" src="https://user-images.githubusercontent.com/57791/100585747-5edbcb00-32ee-11eb-9f4d-01bc51815080.png">

See https://runkit.com/embed/g3xmffywnq7t

The issue can be reproduced locally using nodejs 10 and 12.

Apparently, this is because the [server's certificate chain is incomplete](https://www.ssllabs.com/ssltest/analyze.html?d=thecelo.com):

<img width="1092" alt="Screenshot 2020-11-30 at 09 34 39" src="https://user-images.githubusercontent.com/57791/100586341-4cae5c80-32ef-11eb-8ce0-8c705b2bb506.png">

This issue is not present when using `curl` or `wget` on an OSX machine though.

Let me know if you need more info.

**Comment by bi23com** [comment]
Thank you very much for your feedback.
 I think this issue can be resolved through the following steps:
1. Obtain the missing intermediate certificate
(1) Use openssl to view the server's certificate details
`openssl s_client -connect thecelo.com:443 -servername thecelo.com.com | tee logcertfile`
(2) Then we look for the signing authority of the certificate (the intermediate certificate is the signing authority of the server certificate)
`openssl x509 -in logcertfile -noout -text | grep -i "issuer"`
It will return the URI of a signed certificate. We download the intermediate certificate
`curl --output intermediate.crt http://cacerts.digicert.com/EncryptionEverywhere*******.crt`
Finally, it will be converted into a .pem file.
`openssl x509 -inform DER -in intermediate.crt -out intermediate.pem -text`

2. Use intermediate certificate
It is to carry the intermediate certificate in the process of verifying the certificate.
Two methods are provided here:
(1) Use Node's additional certificate extension configuration to add intermediate certificates
In package.json, we use cross-env to set the Node operating environment
`"start": "cross-env NODE_EXTRA_CA_CERTS=\"/*****/intermediate.pem\" node index.js"`
(2) In the ca option that initiates the request, bring both the local Root certificate and the intermediate certificate.

**Comment by bi23com** [comment]
We have solved the issue with SSL certificate chain, you will not do any more operations, thank you for your feedback!
